### ISSUE TITLE
Caption font not showing in IE11

### ISSUE THREAD

**Issue by moloko** [danielstorey/adapt-blinds#2]
The 'lafayette' font that's used for the captions isn't displaying in IE11:
![2016-10-17 13_38_42-custom components and extensions _ custom components extensions - internet exp](https://cloud.githubusercontent.com/assets/1249597/19437937/7b0304b4-946f-11e6-9323-4510153a9c73.png)

**Comment by danielstorey** [comment]
Does this solve the problem?

[font-face-not-working-with-specific-version-of-internet-explorer-11](http://stackoverflow.com/questions/30174622/font-face-not-working-with-specific-version-of-internet-explorer-11)

**Comment by moloko** [comment]
Unfortunately not - I've checked my settings and I definitely have font downloads enabled. Also, other custom fonts display fine for me...

Having just tried with the console open I notice that I get this:
![2016-10-19 15_29_58-](https://cloud.githubusercontent.com/assets/1249597/19522979/005ee108-9611-11e6-817a-697b47aa2484.png)

Perhaps [this stackoverflow post](https://stackoverflow.com/questions/5587956/make-adobe-fonts-work-with-css3-font-face-in-ie9) might help? Specifically the part about either setting the 'embedded open type' format or including an .eot font?

Either way I don't think the fault lies within your plugin, it's more down to the font embedding in the CSS.
